export const APPOINTMENT_STATUS = Object.freeze({
  PENDIENTE: "PENDIENTE",
  COMPLETADO: "COMPLETADO",
  NO_VINO_AVISO: "NO_VINO_AVISO",
  NO_SHOW: "NO_SHOW",
  CANCELADO: "CANCELADO",
});

export const RESOLVED_STATUSES = new Set([
  APPOINTMENT_STATUS.COMPLETADO,
  APPOINTMENT_STATUS.NO_VINO_AVISO,
  APPOINTMENT_STATUS.NO_SHOW,
  APPOINTMENT_STATUS.CANCELADO,
]);

export const STATUS_TRANSITIONS = Object.freeze({
  [APPOINTMENT_STATUS.PENDIENTE]: new Set([
    APPOINTMENT_STATUS.COMPLETADO,
    APPOINTMENT_STATUS.NO_VINO_AVISO,
    APPOINTMENT_STATUS.NO_SHOW,
    APPOINTMENT_STATUS.CANCELADO,
  ]),
  [APPOINTMENT_STATUS.COMPLETADO]: new Set(),
  [APPOINTMENT_STATUS.NO_VINO_AVISO]: new Set(),
  [APPOINTMENT_STATUS.NO_SHOW]: new Set(),
  [APPOINTMENT_STATUS.CANCELADO]: new Set(),
});
